import os
import json
import time
import requests
import streamlit as st
import streamlit.components.v1 as components
import folium
from folium.plugins import HeatMap
from streamlit_folium import st_folium
from pathlib import Path

import routing

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="ClearRoute Dashboard",
    page_icon="🗺️",
    layout="wide",
)

# ── Data loading ──────────────────────────────────────────────────────────────
REQUIRED_FIELDS = {"lat", "lon", "typ", "konfidenz", "zeitstempel"}

def load_data(source):
    """Loads and validates detection data from a file path or uploaded file."""
    try:
        if hasattr(source, "read"):
            raw = json.load(source)
        else:
            with open(source, encoding="utf-8") as f:
                raw = json.load(f)
    except json.JSONDecodeError:
        st.error("The selected file is not valid JSON. Make sure it was generated correctly by detect.py.")
        st.stop()

    if not isinstance(raw, list) or len(raw) == 0:
        st.error("The file is empty or not in the expected format (should be a list of detections).")
        st.stop()

    missing = REQUIRED_FIELDS - set(raw[0].keys())
    if missing:
        st.error(
            f"Missing fields in the data: **{', '.join(sorted(missing))}**\n\n"
            f"Expected fields: `lat`, `lon`, `typ`, `konfidenz`, `zeitstempel`."
        )
        st.stop()

    return raw

# ── Sidebar — data source selector ───────────────────────────────────────────
with st.sidebar:
    st.header("📂 Data Source")

    dados_dir  = Path("data")
    json_files = sorted(dados_dir.glob("**/*.json")) if dados_dir.exists() else []

    uploaded_file = st.file_uploader(
        "Upload a .json file",
        type="json",
        help="Upload real_data.json generated by detect.py",
    )

    if json_files:
        file_labels   = {p.name: p for p in json_files}
        selected_name = st.selectbox("Or select an existing file:", options=list(file_labels.keys()))
    else:
        selected_name = None
        st.warning("No .json files found in the data/ folder.")

    if uploaded_file:
        data_source  = uploaded_file
        display_name = f"⬆️ {uploaded_file.name}"
    elif selected_name:
        data_source  = file_labels[selected_name]
        display_name = selected_name
    else:
        st.error("No data source available. Add a .json file to the data/ folder.")
        st.stop()

    st.divider()
    st.caption(f"**Loaded:** {display_name}")

data = load_data(data_source)

# ── Session state ─────────────────────────────────────────────────────────────
# addr_cache persists across Streamlit reruns within the same browser session.
# Key: (lat, lon) tuple  →  Value: address string
if "addr_cache" not in st.session_state:
    st.session_state.addr_cache = {}

if "map_mode" not in st.session_state:
    st.session_state.map_mode = "🔥 Heatmap"

# ── Header ────────────────────────────────────────────────────────────────────
st.title("🗺️ ClearRoute Dashboard")
st.caption(f"Real-time urban litter detection monitoring — `{display_name}`")

st.divider()

# ── KPIs ──────────────────────────────────────────────────────────────────────
total_detections = len(data)
distinct_types   = len({d["typ"] for d in data})
avg_confidence   = sum(d["konfidenz"] for d in data) / total_detections

col1, col2, col3 = st.columns(3)
col1.metric(label="📦 Total Detections",      value=total_detections)
col2.metric(label="🗑️ Distinct Litter Types", value=distinct_types)
col3.metric(label="🎯 Average Confidence",    value=f"{avg_confidence:.0%}")

st.divider()

# ── Scoring ───────────────────────────────────────────────────────────────────
TYPE_WEIGHTS = {
    "Müll":       1.0,
    "Verpackung": 1.0,
    "Flasche":    1.2,
    "Becher":     0.8,
}

def calculate_score(detection):
    """Score = confidence × type weight. Higher = clean up first."""
    weight = TYPE_WEIGHTS.get(detection["typ"], 1.0)
    return round(detection["konfidenz"] * weight, 2)

def marker_colour(score):
    """Red for high priority, orange for medium, green for low."""
    if score > 0.7:
        return "#FF4B4B"
    elif score >= 0.4:
        return "#FF8C00"
    return "#2ECC71"

# ── Reverse geocoding ─────────────────────────────────────────────────────────
@st.cache_data   # persists across sessions — each unique (lat, lon) is fetched at most once ever
def get_address(lat, lon):
    """
    Calls Nominatim for a street address.  The sleep respects the 1 req/s rate limit.
    Because of @st.cache_data, this function body only runs ONCE per unique coordinate —
    all subsequent calls (even in different sessions) return the cached result instantly.
    """
    try:
        time.sleep(1)
        url  = f"https://nominatim.openstreetmap.org/reverse?lat={lat}&lon={lon}&format=json"
        resp = requests.get(url, headers={"User-Agent": "ClearRoute-Hackathon"}, timeout=5)
        resp.raise_for_status()
        data = resp.json()

        addr   = data.get("address", {})
        road   = addr.get("road", "")
        number = addr.get("house_number", "")
        city   = (
            addr.get("city")
            or addr.get("town")
            or addr.get("village")
            or addr.get("municipality", "")
        )
        street = f"{road} {number}".strip() if number else road
        if street and city:
            return f"{street}, {city}"
        return data.get("display_name", "Adresse nicht verfügbar")
    except Exception:
        return "Adresse nicht verfügbar"

# ── Map ───────────────────────────────────────────────────────────────────────
def build_map(all_detections, marker_detections, mode="🔥 Heatmap"):
    """
    Builds the Folium map.
    mode == '🔥 Heatmap': heatmap layer + coloured markers on top.
    mode == '📍 Punkte':  coloured markers only, no heatmap.
    """
    m = folium.Map(location=[47.6603, 9.1758], zoom_start=14)

    # Only add the heatmap layer in Heatmap mode
    if mode == "🔥 Heatmap":
        heat_group = folium.FeatureGroup(name="Heatmap", show=True)
        heat_data  = [[d["lat"], d["lon"], d["konfidenz"]] for d in all_detections]
        HeatMap(heat_data, radius=20, blur=15, max_zoom=16).add_to(heat_group)
        heat_group.add_to(m)

    marker_group = folium.FeatureGroup(name="Detections", show=True)
    for d in marker_detections:
        score   = calculate_score(d)
        colour  = marker_colour(score)
        # Read from the in-session cache — instant, no API call
        address = st.session_state.addr_cache.get((d["lat"], d["lon"]), "Loading address...")

        popup_html = (
            f"<b>Address:</b> {address}<br>"
            f"<b>Type:</b> {d['typ']}<br>"
            f"<b>Score:</b> {score}<br>"
            f"<b>Confidence:</b> {d['konfidenz']:.0%}<br>"
            f"<b>Time:</b> {d['zeitstempel']}<br>"
            f"<b>Coords:</b> {d['lat']}, {d['lon']}"
        )

        folium.CircleMarker(
            location=[d["lat"], d["lon"]],
            radius=8,
            color=colour,
            fill=True,
            fill_color=colour,
            fill_opacity=0.85,
            popup=folium.Popup(popup_html, max_width=240),
            tooltip=f"{d['typ']} — score {score}",
        ).add_to(marker_group)

    marker_group.add_to(m)
    folium.LayerControl(position="topright").add_to(m)
    return m

# ── Map section ───────────────────────────────────────────────────────────────
st.subheader("🔥 Detection Map")

# Reserved slot for the address-loading progress bar (filled later in this script)
addr_progress_slot = st.empty()

# Mode toggle — persisted in session_state so it survives filter changes
st.session_state.map_mode = st.radio(
    "Display mode:",
    options=["🔥 Heatmap", "📍 Punkte"],
    index=0 if st.session_state.map_mode == "🔥 Heatmap" else 1,
    horizontal=True,
)

all_types      = sorted({d["typ"] for d in data})
selected_types = st.multiselect(
    "Filter markers by litter type:",
    options=all_types,
    default=all_types,
)
filtered_data = [d for d in data if d["typ"] in selected_types] if selected_types else data

litter_map = build_map(
    all_detections=data,
    marker_detections=filtered_data,
    mode=st.session_state.map_mode,
)
st_folium(litter_map, use_container_width=True, height=520)

st.divider()

# ── Priority Queue ────────────────────────────────────────────────────────────
def build_priority_table(detections):
    """Returns detections sorted by score (highest first), with rank added."""
    scored = []
    for d in detections:
        scored.append({
            "Type":       d["typ"],
            "Lat":        d["lat"],
            "Lon":        d["lon"],
            "Confidence": d["konfidenz"],
            "Time":       d["zeitstempel"],
            "Score":      calculate_score(d),
            # frame_path is only present in real data — None for example data files
            "FramePath":  d.get("frame_path"),
        })
    scored.sort(key=lambda r: r["Score"], reverse=True)
    for i, row in enumerate(scored):
        row["Rank"] = i + 1
    return scored

rows = build_priority_table(data)

st.subheader("🚨 Priority Queue")
with st.expander(f"Show priority list — {len(rows)} detections", expanded=False):
    st.caption("Sorted by cleanup score — top 3 are highlighted for immediate action")
    for row in rows:
        rank    = row["Rank"]
        is_top3 = rank <= 3

        if rank == 1:
            badge = "🥇"; colour = "#FF4B4B"
        elif rank == 2:
            badge = "🥈"; colour = "#FF8C00"
        elif rank == 3:
            badge = "🥉"; colour = "#FFC300"
        else:
            badge = f"#{rank}"; colour = "#555555"

        card_style = (
            f"background-color:{'#1e1e2e' if is_top3 else '#262630'};"
            f"border-left: 4px solid {colour};"
            f"padding: 8px 14px; border-radius: 6px; margin-bottom: 6px;"
            f"font-family: monospace;"
        )
        st.html(
            f"<div style='{card_style}'>"
            f"<span style='color:{colour}; font-weight:bold;'>{badge}</span>&nbsp;&nbsp;"
            f"<b>{row['Type']}</b>&nbsp;&nbsp;|&nbsp;&nbsp;"
            f"📍 {row['Lat']}, {row['Lon']}&nbsp;&nbsp;|&nbsp;&nbsp;"
            f"⏱ {row['Time']}&nbsp;&nbsp;|&nbsp;&nbsp;"
            f"Score: <b>{row['Score']}</b>&nbsp;&nbsp;"
            f"<span style='color:#aaa;'>(conf {row['Confidence']})</span>"
            f"</div>"
        )

st.divider()

# ── Route Planning ─────────────────────────────────────────────────────────────
def get_secret(name):
    """Reads a key from st.secrets, falling back to environment variables."""
    val = ""
    try:
        val = st.secrets.get(name, "")
    except Exception:
        val = ""
    return (val or os.environ.get(name, "")).strip()


_GMAPS_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  html,body{height:100%;margin:0;padding:0;font-family:sans-serif;}
  #map{height:100%;width:100%;background:#1b1b1b;}
  #err{display:none;position:absolute;top:0;left:0;right:0;padding:14px 16px;
       background:#3a1c1c;color:#ffc2c2;font-size:13px;line-height:1.45;z-index:9;}
  #legend{position:absolute;bottom:12px;left:12px;background:rgba(20,20,28,.85);
          color:#fff;padding:8px 10px;border-radius:6px;font-size:12px;z-index:8;}
  #legend div{margin:2px 0;}
  #legend span{display:inline-block;width:12px;height:12px;border-radius:50%;
               margin-right:6px;vertical-align:middle;}
</style>
</head>
<body>
<div id="map"></div>
<div id="err"></div>
<div id="legend"></div>
<script>
const DEPOT = __DEPOT__;
const ROUTES = __ROUTES__;
function showError(msg){
  var e = document.getElementById('err');
  e.innerHTML = msg; e.style.display = 'block';
}
window.gm_authFailure = function(){
  showError('⚠️ Google Maps authentication error. Enable the <b>Maps JavaScript API</b> ' +
            'in Google Cloud and make sure the key restriction allows this origin (localhost:8501).');
};
function initMap(){
  try {
    const map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: DEPOT.lat, lng: DEPOT.lon}, zoom: 13,
      mapTypeControl: false, streetViewControl: false, fullscreenControl: true
    });
    const bounds = new google.maps.LatLngBounds();
    const depotPos = {lat: DEPOT.lat, lng: DEPOT.lon};
    new google.maps.Marker({position: depotPos, map, title: 'Depot (start/end)',
      label: {text: '★', color: 'white', fontSize: '15px'},
      icon: {path: google.maps.SymbolPath.CIRCLE, scale: 13, fillColor: '#111',
             fillOpacity: 1, strokeColor: '#fff', strokeWeight: 2}});
    bounds.extend(depotPos);

    ROUTES.forEach(function(r){
      if (r.polylines && r.polylines.length) {
        let pathCoords = [];
        r.polylines.forEach(function(enc){
          pathCoords = pathCoords.concat(google.maps.geometry.encoding.decodePath(enc));
        });
        new google.maps.Polyline({path: pathCoords, map, strokeColor: r.color,
          strokeOpacity: 0.9, strokeWeight: 5});
      } else {
        const straight = [depotPos]
          .concat(r.stops.map(function(s){return {lat:s.lat, lng:s.lon};}))
          .concat([depotPos]);
        new google.maps.Polyline({path: straight, map, strokeColor: r.color,
          strokeOpacity: 0.8, strokeWeight: 3,
          icons:[{icon:{path:'M 0,-1 0,1', strokeOpacity:1, scale:3}, offset:'0', repeat:'14px'}]});
      }
      r.stops.forEach(function(s){
        const pos = {lat: s.lat, lng: s.lon};
        new google.maps.Marker({position: pos, map,
          title: 'V' + r.vehicle + ' · ' + s.typ + ' · score ' + s.score,
          label: {text: String(s.seq), color: 'white', fontSize: '10px', fontWeight: 'bold'},
          icon: {path: google.maps.SymbolPath.CIRCLE, scale: 9, fillColor: r.color,
                 fillOpacity: 1, strokeColor: '#fff', strokeWeight: 1}});
        bounds.extend(pos);
      });
    });
    if (!bounds.isEmpty()) map.fitBounds(bounds);

    var leg = '<div><span style="background:#111"></span>Depot</div>';
    ROUTES.forEach(function(r){
      leg += '<div><span style="background:' + r.color + '"></span>Vehicle ' +
             r.vehicle + ' (' + r.stops.length + ' stops)</div>';
    });
    document.getElementById('legend').innerHTML = leg;
  } catch (e) {
    showError('Error drawing the map: ' + e.message);
  }
}
window.initMap = initMap;
setTimeout(function(){
  if (!(window.google && window.google.maps)) {
    showError('⏳ Google Maps could not load. Check in Google Cloud: ' +
              '(1) <b>Maps JavaScript API</b> enabled; (2) the key allows this site; ' +
              '(3) billing active. Meanwhile you can switch to OpenStreetMap above.');
  }
}, 6000);
</script>
<script async src="https://maps.googleapis.com/maps/api/js?key=__KEY__&libraries=geometry&callback=initMap"></script>
</body>
</html>"""


def render_google_map_html(routes, depot, api_key):
    """Builds the Google Maps HTML embed with one coloured route per vehicle."""
    depot_json = json.dumps({"lat": depot[0], "lon": depot[1]})
    routes_json = json.dumps([
        {
            "vehicle": r["vehicle"],
            "color": r["color"],
            "polylines": r["polylines"],
            "stops": [
                {"lat": s["lat"], "lon": s["lon"], "seq": s["seq"],
                 "typ": s["typ"], "score": s["score"]}
                for s in r["stops"]
            ],
        }
        for r in routes
    ])
    return (
        _GMAPS_TEMPLATE
        .replace("__DEPOT__", depot_json)
        .replace("__ROUTES__", routes_json)
        .replace("__KEY__", api_key)
    )


def render_folium_routes(routes, depot):
    """Free OpenStreetMap fallback when no Google Maps key is configured."""
    m = folium.Map(location=[depot[0], depot[1]], zoom_start=13)
    folium.Marker(
        [depot[0], depot[1]], tooltip="Depot (start/end)",
        icon=folium.Icon(color="black", icon="home", prefix="fa"),
    ).add_to(m)
    for r in routes:
        pts = [[depot[0], depot[1]]]
        pts += [[s["lat"], s["lon"]] for s in r["stops"]]
        pts += [[depot[0], depot[1]]]
        folium.PolyLine(pts, color=r["color"], weight=4, opacity=0.8,
                        tooltip=f"Vehicle {r['vehicle']}").add_to(m)
        for s in r["stops"]:
            folium.CircleMarker(
                [s["lat"], s["lon"]], radius=7, color=r["color"], fill=True,
                fill_color=r["color"], fill_opacity=0.9,
                tooltip=f"#{s['seq']} · {s['typ']} · score {s['score']}",
            ).add_to(m)
    return m


st.subheader("🚚 Route Planning")
st.caption(f"Base (start and end for all vehicles): **{routing.DEPOT_ADDRESS}**")

route_points = [
    {"id": i, "lat": d["lat"], "lon": d["lon"], "typ": d["typ"],
     "konfidenz": d["konfidenz"], "score": calculate_score(d)}
    for i, d in enumerate(data)
]

anthropic_key = get_secret("ANTHROPIC_API_KEY")
gmaps_key     = get_secret("GOOGLE_MAPS_API_KEY")

col_ctrl, col_status = st.columns([1, 2])
with col_ctrl:
    n_vehicles = st.number_input(
        "Vehicles available",
        min_value=1, max_value=max(1, len(route_points)),
        value=min(3, max(1, len(route_points))), step=1,
    )
    generate = st.button("🧭 Generate routes", type="primary", use_container_width=True)
with col_status:
    st.markdown(
        f"- AI (Claude): {'✅ configured' if anthropic_key else '⚠️ missing `ANTHROPIC_API_KEY`'}\n"
        f"- Google Maps: {'✅ configured' if gmaps_key else '⚠️ missing `GOOGLE_MAPS_API_KEY`'}"
    )
    if not anthropic_key or not gmaps_key:
        st.caption("Keys go in `.streamlit/secrets.toml`. Without them a local assignment "
                   "and an OpenStreetMap preview are used.")

if generate:
    with st.spinner("Geocoding the depot and generating routes…"):
        depot = routing.geocode_depot(routing.DEPOT_ADDRESS, gmaps_key)
        routes, info = routing.plan_routes(
            route_points, int(n_vehicles), depot,
            anthropic_key=anthropic_key, gmaps_key=gmaps_key,
        )
    st.session_state["routes_result"] = {"routes": routes, "info": info, "depot": depot}

result = st.session_state.get("routes_result")
if result and result["routes"]:
    routes, info, depot = result["routes"], result["info"], result["depot"]

    engine = {"claude": "Claude (AI)", "fallback": "local assignment (no AI)"}.get(
        info["engine"], "—")
    real = routes and all(r["directions_ok"] for r in routes)
    total_km = sum(r["distance_m"] for r in routes) / 1000
    summary = f"✅ {len(routes)} routes generated · {len(route_points)} stops · engine: {engine}"
    if real:
        summary += f" · {total_km:.1f} km total"
    st.success(summary)
    for w in info.get("warnings", []):
        st.warning(w)

    # ── Route map ──
    st.markdown("#### 🗺️ Route map per vehicle")
    if gmaps_key:
        provider = st.radio(
            "Map provider", ["Google Maps", "OpenStreetMap"],
            horizontal=True, key="map_provider",
            help="If Google Maps shows blank, enable the Maps JavaScript API "
                 "or use OpenStreetMap (always works).",
        )
    else:
        provider = "OpenStreetMap"

    if provider == "Google Maps":
        components.html(render_google_map_html(routes, depot, gmaps_key), height=580)
        st.caption("If the box shows blank, it will display the reason (usually the "
                   "**Maps JavaScript API** is not enabled). You can switch to OpenStreetMap above.")
    else:
        st_folium(render_folium_routes(routes, depot),
                  use_container_width=True, height=540, key="osm_routes_map")

    for r in routes:
        header = f"Vehicle {r['vehicle']} — {len(r['stops'])} stops"
        if r["directions_ok"]:
            header += f"  ·  {r['distance_m']/1000:.1f} km  ·  {r['duration_s']//60} min"
        with st.expander(header):
            order = " → ".join(f"#{s['seq']} {s['typ']}" for s in r["stops"]) or "(no stops)"
            st.markdown(f"**Visit order:** {order}")
            if r.get("reasoning"):
                st.markdown(f"**Reasoning (AI):** {r['reasoning']}")
            if not r["directions_ok"] and gmaps_key:
                st.caption("Route shown as a straight line (Directions unavailable for this route).")

st.divider()

# ── Detail View ───────────────────────────────────────────────────────────────
def show_detail(detection):
    """Renders the full detail panel for a single detection."""
    col_info, col_img = st.columns([1, 1], gap="large")

    with col_info:
        # Read from cache — instant if already loaded, 'Loading...' if not yet
        address = st.session_state.addr_cache.get(
            (detection["Lat"], detection["Lon"]), "Loading address..."
        )
        st.markdown("**Detection Info**")
        st.markdown(f"- **Address:** {address}")
        st.markdown(f"- **Type:** {detection['Type']}")
        st.markdown(f"- **Coordinates:** {detection['Lat']}, {detection['Lon']}")
        st.markdown(f"- **Confidence:** {detection['Confidence']:.0%}")
        st.markdown(f"- **Score:** {detection['Score']}")
        st.markdown(f"- **Timestamp:** {detection['Time']}")
        st.markdown(f"- **Rank:** #{detection['Rank']} in the priority queue")

    with col_img:
        st.markdown("**Annotated Image**")
        frame_path = detection.get("FramePath")
        if frame_path and Path(frame_path).exists():
            # Real data from detect.py — show the YOLO-annotated frame
            st.image(
                frame_path,
                caption=f"Erkannter Müll — {detection['Time']}",
                use_container_width=True,
            )
        else:
            # Demo data (dados_exemplo.json) has no images — keep the placeholder
            st.info(
                "📷 Image will be available after YOLO integration.",
                icon="🔧",
            )

st.subheader("🔍 Detail View")
st.caption("Select a detection from the priority queue to inspect it")

options      = [f"#{r['Rank']} — {r['Type']} @ {r['Time']}" for r in rows]
chosen_label = st.selectbox("Detection", options, index=0)
show_detail(rows[options.index(chosen_label)])

# ── Progressive address loading ───────────────────────────────────────────────
# This block runs AFTER the entire dashboard has been sent to the browser.
# It fills addr_progress_slot (the reserved slot above the map) with a live
# progress bar, fetches each missing address, then triggers one rerun so the
# map and detail panel refresh with real addresses in their popups.

unique_coords = list({(d["lat"], d["lon"]) for d in data})
unloaded      = [(lat, lon) for lat, lon in unique_coords
                 if (lat, lon) not in st.session_state.addr_cache]

if unloaded:
    n_total = len(unique_coords)

    for lat, lon in unloaded:
        n_done = len(st.session_state.addr_cache)
        # Update the slot reserved above the map
        addr_progress_slot.progress(
            min(n_done / n_total, 1.0),
            text=f"Loading addresses... ({n_done}/{n_total})",
        )
        # get_address is @st.cache_data — sleep only runs on first-ever fetch
        st.session_state.addr_cache[(lat, lon)] = get_address(lat, lon)

    # All addresses are now in session_state — clear bar and refresh the map
    addr_progress_slot.empty()
    st.rerun()
