import json
import time
import requests
import streamlit as st
import folium
from folium.plugins import HeatMap
from streamlit_folium import st_folium
from pathlib import Path

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="ClearRoute Dashboard",
    page_icon="🗺️",
    layout="wide",
)

# ── Data loading ──────────────────────────────────────────────────────────────
REQUIRED_FIELDS = {"lat", "lon", "typ", "konfidenz", "zeitstempel"}

def load_data(source):
    """Loads and validates detection data from a file path or uploaded file."""
    try:
        if hasattr(source, "read"):
            raw = json.load(source)
        else:
            with open(source, encoding="utf-8") as f:
                raw = json.load(f)
    except json.JSONDecodeError:
        st.error("The selected file is not valid JSON. Make sure it was generated correctly by detect.py.")
        st.stop()

    if not isinstance(raw, list) or len(raw) == 0:
        st.error("The file is empty or not in the expected format (should be a list of detections).")
        st.stop()

    missing = REQUIRED_FIELDS - set(raw[0].keys())
    if missing:
        st.error(
            f"Missing fields in the data: **{', '.join(sorted(missing))}**\n\n"
            f"Expected fields: `lat`, `lon`, `typ`, `konfidenz`, `zeitstempel`."
        )
        st.stop()

    return raw

# ── Sidebar — data source selector ───────────────────────────────────────────
with st.sidebar:
    st.header("📂 Data Source")

    dados_dir  = Path("dados")
    json_files = sorted(dados_dir.glob("*.json")) if dados_dir.exists() else []
    json_files += [p for p in Path(".").glob("*.json") if p not in json_files]

    uploaded_file = st.file_uploader(
        "Upload a .json file",
        type="json",
        help="Upload dados_reais.json generated by detect.py",
    )

    if json_files:
        file_labels   = {p.name: p for p in json_files}
        selected_name = st.selectbox("Or select an existing file:", options=list(file_labels.keys()))
    else:
        selected_name = None
        st.warning("No .json files found in the dados/ folder.")

    if uploaded_file:
        data_source  = uploaded_file
        display_name = f"⬆️ {uploaded_file.name}"
    elif selected_name:
        data_source  = file_labels[selected_name]
        display_name = selected_name
    else:
        st.error("No data source available. Add a .json file to the dados/ folder.")
        st.stop()

    st.divider()
    st.caption(f"**Loaded:** {display_name}")

data = load_data(data_source)

# ── Session state ─────────────────────────────────────────────────────────────
# addr_cache persists across Streamlit reruns within the same browser session.
# Key: (lat, lon) tuple  →  Value: address string
if "addr_cache" not in st.session_state:
    st.session_state.addr_cache = {}

# ── Header ────────────────────────────────────────────────────────────────────
st.title("🗺️ ClearRoute Dashboard")
st.caption(f"Real-time urban litter detection monitoring — `{display_name}`")

st.divider()

# ── KPIs ──────────────────────────────────────────────────────────────────────
total_detections = len(data)
distinct_types   = len({d["typ"] for d in data})
avg_confidence   = sum(d["konfidenz"] for d in data) / total_detections

col1, col2, col3 = st.columns(3)
col1.metric(label="📦 Total Detections",      value=total_detections)
col2.metric(label="🗑️ Distinct Litter Types", value=distinct_types)
col3.metric(label="🎯 Average Confidence",    value=f"{avg_confidence:.0%}")

st.divider()

# ── Scoring ───────────────────────────────────────────────────────────────────
TYPE_WEIGHTS = {
    "Müll":       1.0,
    "Verpackung": 1.0,
    "Flasche":    1.2,
    "Becher":     0.8,
}

def calculate_score(detection):
    """Score = confidence × type weight. Higher = clean up first."""
    weight = TYPE_WEIGHTS.get(detection["typ"], 1.0)
    return round(detection["konfidenz"] * weight, 2)

def marker_colour(score):
    """Red for high priority, orange for medium, green for low."""
    if score > 0.7:
        return "#FF4B4B"
    elif score >= 0.4:
        return "#FF8C00"
    return "#2ECC71"

# ── Reverse geocoding ─────────────────────────────────────────────────────────
@st.cache_data   # persists across sessions — each unique (lat, lon) is fetched at most once ever
def get_address(lat, lon):
    """
    Calls Nominatim for a street address.  The sleep respects the 1 req/s rate limit.
    Because of @st.cache_data, this function body only runs ONCE per unique coordinate —
    all subsequent calls (even in different sessions) return the cached result instantly.
    """
    try:
        time.sleep(1)
        url  = f"https://nominatim.openstreetmap.org/reverse?lat={lat}&lon={lon}&format=json"
        resp = requests.get(url, headers={"User-Agent": "ClearRoute-Hackathon"}, timeout=5)
        resp.raise_for_status()
        data = resp.json()

        addr   = data.get("address", {})
        road   = addr.get("road", "")
        number = addr.get("house_number", "")
        city   = (
            addr.get("city")
            or addr.get("town")
            or addr.get("village")
            or addr.get("municipality", "")
        )
        street = f"{road} {number}".strip() if number else road
        if street and city:
            return f"{street}, {city}"
        return data.get("display_name", "Adresse nicht verfügbar")
    except Exception:
        return "Adresse nicht verfügbar"

# ── Map ───────────────────────────────────────────────────────────────────────
def build_map(all_detections, marker_detections):
    """
    Builds the Folium map.
    Addresses come from st.session_state.addr_cache — no API calls happen here.
    On first load they show 'Loading address...'; after geocoding they show real addresses.
    """
    m = folium.Map(location=[47.6603, 9.1758], zoom_start=14)

    heat_group = folium.FeatureGroup(name="Heatmap", show=True)
    heat_data  = [[d["lat"], d["lon"], d["konfidenz"]] for d in all_detections]
    HeatMap(heat_data, radius=20, blur=15, max_zoom=16).add_to(heat_group)
    heat_group.add_to(m)

    marker_group = folium.FeatureGroup(name="Detections", show=True)
    for d in marker_detections:
        score   = calculate_score(d)
        colour  = marker_colour(score)
        # Read from the in-session cache — instant, no API call
        address = st.session_state.addr_cache.get((d["lat"], d["lon"]), "Loading address...")

        popup_html = (
            f"<b>Address:</b> {address}<br>"
            f"<b>Type:</b> {d['typ']}<br>"
            f"<b>Score:</b> {score}<br>"
            f"<b>Confidence:</b> {d['konfidenz']:.0%}<br>"
            f"<b>Time:</b> {d['zeitstempel']}<br>"
            f"<b>Coords:</b> {d['lat']}, {d['lon']}"
        )

        folium.CircleMarker(
            location=[d["lat"], d["lon"]],
            radius=8,
            color=colour,
            fill=True,
            fill_color=colour,
            fill_opacity=0.85,
            popup=folium.Popup(popup_html, max_width=240),
            tooltip=f"{d['typ']} — score {score}",
        ).add_to(marker_group)

    marker_group.add_to(m)
    folium.LayerControl(position="topright").add_to(m)
    return m

# ── Map section ───────────────────────────────────────────────────────────────
st.subheader("🔥 Detection Map")

# This empty slot is reserved NOW (above the map in the layout).
# The loading loop at the bottom of this script will fill it with a progress bar
# while addresses are being fetched — after the full dashboard has already rendered.
addr_progress_slot = st.empty()

all_types      = sorted({d["typ"] for d in data})
selected_types = st.multiselect(
    "Filter markers by litter type:",
    options=all_types,
    default=all_types,
)
filtered_data = [d for d in data if d["typ"] in selected_types] if selected_types else data

litter_map = build_map(all_detections=data, marker_detections=filtered_data)
st_folium(litter_map, use_container_width=True, height=520)

st.divider()

# ── Priority Queue ────────────────────────────────────────────────────────────
def build_priority_table(detections):
    """Returns detections sorted by score (highest first), with rank added."""
    scored = []
    for d in detections:
        scored.append({
            "Type":       d["typ"],
            "Lat":        d["lat"],
            "Lon":        d["lon"],
            "Confidence": d["konfidenz"],
            "Time":       d["zeitstempel"],
            "Score":      calculate_score(d),
            # frame_path is only present in real data — None for dados_exemplo.json
            "FramePath":  d.get("frame_path"),
        })
    scored.sort(key=lambda r: r["Score"], reverse=True)
    for i, row in enumerate(scored):
        row["Rank"] = i + 1
    return scored

st.subheader("🚨 Priority Queue")
st.caption("Sorted by cleanup score — top 3 are highlighted for immediate action")

rows = build_priority_table(data)

for row in rows:
    rank    = row["Rank"]
    is_top3 = rank <= 3

    if rank == 1:
        badge = "🥇"; colour = "#FF4B4B"
    elif rank == 2:
        badge = "🥈"; colour = "#FF8C00"
    elif rank == 3:
        badge = "🥉"; colour = "#FFC300"
    else:
        badge = f"#{rank}"; colour = "#555555"

    card_style = (
        f"background-color:{'#1e1e2e' if is_top3 else '#262630'};"
        f"border-left: 4px solid {colour};"
        f"padding: 8px 14px; border-radius: 6px; margin-bottom: 6px;"
        f"font-family: monospace;"
    )
    st.html(
        f"<div style='{card_style}'>"
        f"<span style='color:{colour}; font-weight:bold;'>{badge}</span>&nbsp;&nbsp;"
        f"<b>{row['Type']}</b>&nbsp;&nbsp;|&nbsp;&nbsp;"
        f"📍 {row['Lat']}, {row['Lon']}&nbsp;&nbsp;|&nbsp;&nbsp;"
        f"⏱ {row['Time']}&nbsp;&nbsp;|&nbsp;&nbsp;"
        f"Score: <b>{row['Score']}</b>&nbsp;&nbsp;"
        f"<span style='color:#aaa;'>(conf {row['Confidence']})</span>"
        f"</div>"
    )

st.divider()

# ── Detail View ───────────────────────────────────────────────────────────────
def show_detail(detection):
    """Renders the full detail panel for a single detection."""
    col_info, col_img = st.columns([1, 1], gap="large")

    with col_info:
        # Read from cache — instant if already loaded, 'Loading...' if not yet
        address = st.session_state.addr_cache.get(
            (detection["Lat"], detection["Lon"]), "Loading address..."
        )
        st.markdown("**Detection Info**")
        st.markdown(f"- **Address:** {address}")
        st.markdown(f"- **Type:** {detection['Type']}")
        st.markdown(f"- **Coordinates:** {detection['Lat']}, {detection['Lon']}")
        st.markdown(f"- **Confidence:** {detection['Confidence']:.0%}")
        st.markdown(f"- **Score:** {detection['Score']}")
        st.markdown(f"- **Timestamp:** {detection['Time']}")
        st.markdown(f"- **Rank:** #{detection['Rank']} in the priority queue")

    with col_img:
        st.markdown("**Annotated Image**")
        frame_path = detection.get("FramePath")
        if frame_path and Path(frame_path).exists():
            # Real data from detect.py — show the YOLO-annotated frame
            st.image(
                frame_path,
                caption=f"Erkannter Müll — {detection['Time']}",
                use_container_width=True,
            )
        else:
            # Demo data (dados_exemplo.json) has no images — keep the placeholder
            st.info(
                "📷 Image will be available after YOLO integration.\n\n"
                "*(Bild wird nach YOLO-Integration verfügbar)*",
                icon="🔧",
            )

st.subheader("🔍 Detail View")
st.caption("Select a detection from the priority queue to inspect it")

options      = [f"#{r['Rank']} — {r['Type']} @ {r['Time']}" for r in rows]
chosen_label = st.selectbox("Detection", options, index=0)
show_detail(rows[options.index(chosen_label)])

# ── Progressive address loading ───────────────────────────────────────────────
# This block runs AFTER the entire dashboard has been sent to the browser.
# It fills addr_progress_slot (the reserved slot above the map) with a live
# progress bar, fetches each missing address, then triggers one rerun so the
# map and detail panel refresh with real addresses in their popups.

unique_coords = list({(d["lat"], d["lon"]) for d in data})
unloaded      = [(lat, lon) for lat, lon in unique_coords
                 if (lat, lon) not in st.session_state.addr_cache]

if unloaded:
    n_total = len(unique_coords)

    for lat, lon in unloaded:
        n_done = len(st.session_state.addr_cache)
        # Update the slot reserved above the map
        addr_progress_slot.progress(
            n_done / n_total,
            text=f"Loading addresses... ({n_done}/{n_total})",
        )
        # get_address is @st.cache_data — sleep only runs on first-ever fetch
        st.session_state.addr_cache[(lat, lon)] = get_address(lat, lon)

    # All addresses are now in session_state — clear bar and refresh the map
    addr_progress_slot.empty()
    st.rerun()
